---
ID: "b343188f-3162-4f3c-80c9-e1d3237b6d20"
Parent: "db196c12-b8bd-451d-a1f5-05e7c6d74721"
Template: "db196c12-b8bd-451d-a1f5-05e7c6d74721"
Path: /sitecore/templates/Feature/Blog/Interface Templates/_Portfolio/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180926T070149Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
