//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synthesis.Model.Feature.Blog.FolderTemplates {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Folder Templates/Blog Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{9EE4B539-5E3F-40DC-84AF-DD5554D8AA88}", "cRB8vUNKONc6I81oarkz6LiIOfs=", "Default Configuration")]
    public partial interface IBlogFolderItem : Synthesis.IStandardTemplateItem {
    }
}
namespace Synthesis.Model.Feature.Blog.InterfaceTemplates {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Article template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F93B8AB4-13E9-4928-B8B5-139B566434E2}", "/eKyFTNnNdYb58XjHtL1qOA3TrQ=", "Default Configuration")]
    public partial interface I_ArticleItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the ArticleTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articletitle")]
        Synthesis.FieldTypes.Interfaces.ITextField ArticleTitle {
            get;
        }
        
        /// <summary>Represents the ArticleBody field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articlebody")]
        Synthesis.FieldTypes.Interfaces.IRichTextField ArticleBody {
            get;
        }
        
        /// <summary>Represents the ArticleSummary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articlesummary")]
        Synthesis.FieldTypes.Interfaces.ITextField ArticleSummary {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Header template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{8A805A6F-BA64-4AF8-8948-66DF82CE9A7B}", "OPKoydwBYY2FOIOKHYymvEen7Rw=", "Default Configuration")]
    public partial interface I_HeaderItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        Synthesis.FieldTypes.Interfaces.ITextField Text {
            get;
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        Synthesis.FieldTypes.Interfaces.IImageField Image {
            get;
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        Synthesis.FieldTypes.Interfaces.ITextField Title {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Page template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{3AD8CB71-52F1-47EF-B7C8-3F7A12EDA2C8}", "ltssB7djTewVtA9avhDw7VNEACQ=", "Default Configuration")]
    public partial interface I_PageItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        Synthesis.FieldTypes.Interfaces.ITextField Title {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Portfolio template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{DB196C12-B8BD-451D-A1F5-05E7C6D74721}", "7fL5Q7R7/lmKpP21at6Pylt7pa4=", "Default Configuration")]
    public partial interface I_PortfolioItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the PortfolioTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("portfoliotitle")]
        Synthesis.FieldTypes.Interfaces.ITextField PortfolioTitle {
            get;
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        Synthesis.FieldTypes.Interfaces.IImageField Image {
            get;
        }
        
        /// <summary>Represents the PortfolioBody field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("portfoliobody")]
        Synthesis.FieldTypes.Interfaces.IRichTextField PortfolioBody {
            get;
        }
    }
}
namespace Synthesis.Model.Foundation.MultiTenant.FolderTemplates {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{35DDD80D-E8A2-4080-A160-32C9C155152C}", "/vijYr1A2wWmxH0H3mVgLPeRWG8=", "Default Configuration")]
    public partial interface ISiteFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{FF290707-F5EF-48BF-BE32-B350E364DBFC}", "zTibeNJ7DXqA129mnBpzo7ptlWk=", "Default Configuration")]
    public partial interface ISiteItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Tenant Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{D8CD7BB9-98F9-4FF1-855D-E335B09CF744}", "cihbJ7SDlmY3rP/cYpvx9fImtU0=", "Default Configuration")]
    public partial interface ITenantFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Tenant template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{E76133A6-2F62-48E8-A37A-C0D1D0723832}", "H8NP+KCHqfiMt3cNw6Avbwi0eN8=", "Default Configuration")]
    public partial interface ITenantItem : Synthesis.IStandardTemplateItem {
    }
}
namespace Synthesis.Model.Project.Example.PageTypeTemplate {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/About template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{4E366B25-F5DF-44D6-A443-F33F75522C73}", "0Kp37rMzPJ/yHp4yhj8g0zbMQes=", "Default Configuration")]
    public partial interface IAboutItem : global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Article template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{1586488A-70EE-4B20-8D6A-163C70D566CC}", "8E1+RCLGXEzHRgawOznvEP0nlLI=", "Default Configuration")]
    public partial interface IArticleItem : global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_ArticleItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Blog template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{B131E0EC-0E5C-4811-B01F-2012A0066A85}", "mfs45ACV5iHg9N/7nTrGoYR+9pQ=", "Default Configuration")]
    public partial interface IBlogItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Bucket Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{59191524-2EFC-4B12-A0BC-18C3B1E951C0}", "wHsDY8xDY/FMKKNoQTH5HK1SvsU=", "Default Configuration")]
    public partial interface IBucketFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Bucketable Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{CA7C2876-A42D-4635-894D-4662294BAAC9}", "XufgCcofNBVU94EbAzWOYx/GNn0=", "Default Configuration")]
    public partial interface IBucketableItemItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Contact template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{BB904876-F2DD-4A54-B919-12E1FE05FAF8}", "zK+IEYalMargaboFvSc/9uZBeSU=", "Default Configuration")]
    public partial interface IContactItem : global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Home template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{11091972-0EFA-4E48-9550-ACCE7FA64B03}", "rVgeL7rnwnAHESwsa+3STBy7w5c=", "Default Configuration")]
    public partial interface IHomeItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Portfolio template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{96BF0B0D-7FFD-47D3-854E-C9E1C98DF8DF}", "WYLMwRHPxF4H7Jt1H/KwbWnuA4w=", "Default Configuration")]
    public partial interface IPortfolioItem : global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PortfolioItem, global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PageItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IBucketableItemItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Portfolios template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A8470C4A-7757-464D-9573-2B685AC6A2F2}", "YrmsefHy5WUt9sYunoKOzq0wkAw=", "Default Configuration")]
    public partial interface IPortfoliosItem : global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PageItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IBucketFolderItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/test-area template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{AF871E1D-D32E-4090-AB97-BCDE8565780D}", "mk1icfGqlQG1IPRwfCtZZEueSgI=", "Default Configuration")]
    public partial interface ItestareaItem : Synthesis.IStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synthesis.Model.Concrete.Feature.Blog.FolderTemplates {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Folder Templates/Blog Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class BlogFolder : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Feature.Blog.FolderTemplates.IBlogFolderItem {
        
        public BlogFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public BlogFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Blog Folder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{9EE4B539-5E3F-40DC-84AF-DD5554D8AA88}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class BlogFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{9EE4B539-5E3F-40DC-84AF-DD5554D8AA88}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new BlogFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new BlogFolder(searchFields);
        }
    }
}
namespace Synthesis.Model.Concrete.Feature.Blog.InterfaceTemplates {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Article template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _Article : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_ArticleItem {
        
        private Synthesis.FieldTypes.TextField _articleTitle;
        
        private Synthesis.FieldTypes.RichTextField _articleBody;
        
        private Synthesis.FieldTypes.TextField _articleSummary;
        
        public _Article(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _Article(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Article";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F93B8AB4-13E9-4928-B8B5-139B566434E2}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the ArticleTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articletitle")]
        public Synthesis.FieldTypes.Interfaces.ITextField ArticleTitle {
            get {
                if (_articleTitle == null) {
                    _articleTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9471A174-E608-4D72-9D4B-0614F1707A08}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Article", "ArticleTitle"), this.GetSearchFieldValue("articletitle"));
                }
                return _articleTitle;
            }
        }
        
        /// <summary>Represents the ArticleBody field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articlebody")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField ArticleBody {
            get {
                if (_articleBody == null) {
                    _articleBody = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{86E8C424-4514-4E47-BB9B-A41F39112AE2}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Article", "ArticleBody"), this.GetSearchFieldValue("articlebody"));
                }
                return _articleBody;
            }
        }
        
        /// <summary>Represents the ArticleSummary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articlesummary")]
        public Synthesis.FieldTypes.Interfaces.ITextField ArticleSummary {
            get {
                if (_articleSummary == null) {
                    _articleSummary = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E8C27BD1-5354-4408-8966-D473D6C12B18}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Article", "ArticleSummary"), this.GetSearchFieldValue("articlesummary"));
                }
                return _articleSummary;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _ArticleInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F93B8AB4-13E9-4928-B8B5-139B566434E2}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _Article(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _Article(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Header template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _Header : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_HeaderItem {
        
        private Synthesis.FieldTypes.TextField _text;
        
        private Synthesis.FieldTypes.ImageField _image;
        
        private Synthesis.FieldTypes.TextField _title;
        
        public _Header(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _Header(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Header";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{8A805A6F-BA64-4AF8-8948-66DF82CE9A7B}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        public Synthesis.FieldTypes.Interfaces.ITextField Text {
            get {
                if (_text == null) {
                    _text = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{4C82A50C-6E3F-4A3D-860F-8CD0C1D8ACB1}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Header", "Text"), this.GetSearchFieldValue("text"));
                }
                return _text;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image {
            get {
                if (_image == null) {
                    _image = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E9DE63BC-6284-4805-9F7A-00C48BBE39D3}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Header", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{D1BF0542-E556-4D0D-BBA2-15D01B604672}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Header", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _HeaderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{8A805A6F-BA64-4AF8-8948-66DF82CE9A7B}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _Header(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _Header(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Page template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _Page : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PageItem {
        
        private Synthesis.FieldTypes.TextField _title;
        
        public _Page(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _Page(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Page";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{3AD8CB71-52F1-47EF-B7C8-3F7A12EDA2C8}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0ED549A-2C9A-4D45-9D47-C670BB6B0C54}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Page", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _PageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{3AD8CB71-52F1-47EF-B7C8-3F7A12EDA2C8}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _Page(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _Page(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Blog/Interface Templates/_Portfolio template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _Portfolio : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Feature.Blog.InterfaceTemplates.I_PortfolioItem {
        
        private Synthesis.FieldTypes.TextField _portfolioTitle;
        
        private Synthesis.FieldTypes.ImageField _image;
        
        private Synthesis.FieldTypes.RichTextField _portfolioBody;
        
        public _Portfolio(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _Portfolio(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Portfolio";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{DB196C12-B8BD-451D-A1F5-05E7C6D74721}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the PortfolioTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("portfoliotitle")]
        public Synthesis.FieldTypes.Interfaces.ITextField PortfolioTitle {
            get {
                if (_portfolioTitle == null) {
                    _portfolioTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{480B41FD-DE3A-49FE-ABA9-EFABCE9FEC87}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Portfolio", "PortfolioTitle"), this.GetSearchFieldValue("portfoliotitle"));
                }
                return _portfolioTitle;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image {
            get {
                if (_image == null) {
                    _image = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{89FA71B6-5B2B-49A1-A082-79DE07A2A24E}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Portfolio", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image;
            }
        }
        
        /// <summary>Represents the PortfolioBody field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("portfoliobody")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField PortfolioBody {
            get {
                if (_portfolioBody == null) {
                    _portfolioBody = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F7E753D8-1700-426F-98A0-D0C8D4649B70}"], "/sitecore/templates/Feature/Blog/Interface Templates/_Portfolio", "PortfolioBody"), this.GetSearchFieldValue("portfoliobody"));
                }
                return _portfolioBody;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _PortfolioInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{DB196C12-B8BD-451D-A1F5-05E7C6D74721}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _Portfolio(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _Portfolio(searchFields);
        }
    }
}
namespace Synthesis.Model.Concrete.Foundation.MultiTenant.FolderTemplates {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Site : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Foundation.MultiTenant.FolderTemplates.ISiteItem {
        
        public Site(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Site(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Site";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{FF290707-F5EF-48BF-BE32-B350E364DBFC}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class SiteFolder : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Foundation.MultiTenant.FolderTemplates.ISiteFolderItem {
        
        public SiteFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SiteFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Site Folder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{35DDD80D-E8A2-4080-A160-32C9C155152C}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class SiteFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{35DDD80D-E8A2-4080-A160-32C9C155152C}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SiteFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SiteFolder(searchFields);
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class SiteInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{FF290707-F5EF-48BF-BE32-B350E364DBFC}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Site(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Site(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Tenant template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Tenant : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Foundation.MultiTenant.FolderTemplates.ITenantItem {
        
        public Tenant(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Tenant(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Tenant";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{E76133A6-2F62-48E8-A37A-C0D1D0723832}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/MultiTenant/Folder Templates/Tenant Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class TenantFolder : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Foundation.MultiTenant.FolderTemplates.ITenantFolderItem {
        
        public TenantFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public TenantFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Tenant Folder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{D8CD7BB9-98F9-4FF1-855D-E335B09CF744}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class TenantFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{D8CD7BB9-98F9-4FF1-855D-E335B09CF744}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new TenantFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new TenantFolder(searchFields);
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class TenantInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{E76133A6-2F62-48E8-A37A-C0D1D0723832}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Tenant(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Tenant(searchFields);
        }
    }
}
namespace Synthesis.Model.Concrete.Project.Example.PageTypeTemplate {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/About template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class About : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IAboutItem {
        
        private Synthesis.FieldTypes.TextField _title;
        
        public About(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public About(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "About";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{4E366B25-F5DF-44D6-A443-F33F75522C73}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0ED549A-2C9A-4D45-9D47-C670BB6B0C54}"], "/sitecore/templates/Project/Example/Page Type Template/About", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class AboutInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{4E366B25-F5DF-44D6-A443-F33F75522C73}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new About(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new About(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Article template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Article : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IArticleItem {
        
        private Synthesis.FieldTypes.TextField _articleTitle;
        
        private Synthesis.FieldTypes.RichTextField _articleBody;
        
        private Synthesis.FieldTypes.TextField _articleSummary;
        
        public Article(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Article(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Article";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{1586488A-70EE-4B20-8D6A-163C70D566CC}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the ArticleTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articletitle")]
        public Synthesis.FieldTypes.Interfaces.ITextField ArticleTitle {
            get {
                if (_articleTitle == null) {
                    _articleTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9471A174-E608-4D72-9D4B-0614F1707A08}"], "/sitecore/templates/Project/Example/Page Type Template/Article", "ArticleTitle"), this.GetSearchFieldValue("articletitle"));
                }
                return _articleTitle;
            }
        }
        
        /// <summary>Represents the ArticleBody field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articlebody")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField ArticleBody {
            get {
                if (_articleBody == null) {
                    _articleBody = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{86E8C424-4514-4E47-BB9B-A41F39112AE2}"], "/sitecore/templates/Project/Example/Page Type Template/Article", "ArticleBody"), this.GetSearchFieldValue("articlebody"));
                }
                return _articleBody;
            }
        }
        
        /// <summary>Represents the ArticleSummary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("articlesummary")]
        public Synthesis.FieldTypes.Interfaces.ITextField ArticleSummary {
            get {
                if (_articleSummary == null) {
                    _articleSummary = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E8C27BD1-5354-4408-8966-D473D6C12B18}"], "/sitecore/templates/Project/Example/Page Type Template/Article", "ArticleSummary"), this.GetSearchFieldValue("articlesummary"));
                }
                return _articleSummary;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class ArticleInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{1586488A-70EE-4B20-8D6A-163C70D566CC}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Article(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Article(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Blog template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Blog : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IBlogItem {
        
        public Blog(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Blog(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Blog";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{B131E0EC-0E5C-4811-B01F-2012A0066A85}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class BlogInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{B131E0EC-0E5C-4811-B01F-2012A0066A85}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Blog(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Blog(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Bucket Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class BucketFolder : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IBucketFolderItem {
        
        public BucketFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public BucketFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Bucket Folder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{59191524-2EFC-4B12-A0BC-18C3B1E951C0}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class BucketFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{59191524-2EFC-4B12-A0BC-18C3B1E951C0}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new BucketFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new BucketFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Bucketable Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class BucketableItem : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IBucketableItemItem {
        
        public BucketableItem(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public BucketableItem(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Bucketable Item";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{CA7C2876-A42D-4635-894D-4662294BAAC9}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class BucketableItemInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{CA7C2876-A42D-4635-894D-4662294BAAC9}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new BucketableItem(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new BucketableItem(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Contact template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Contact : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IContactItem {
        
        private Synthesis.FieldTypes.TextField _title;
        
        public Contact(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Contact(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Contact";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{BB904876-F2DD-4A54-B919-12E1FE05FAF8}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0ED549A-2C9A-4D45-9D47-C670BB6B0C54}"], "/sitecore/templates/Project/Example/Page Type Template/Contact", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class ContactInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{BB904876-F2DD-4A54-B919-12E1FE05FAF8}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Contact(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Contact(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Home template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Home : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IHomeItem {
        
        public Home(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Home(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Home";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{11091972-0EFA-4E48-9550-ACCE7FA64B03}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class HomeInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{11091972-0EFA-4E48-9550-ACCE7FA64B03}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Home(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Home(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Portfolio template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Portfolio : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IPortfolioItem {
        
        private Synthesis.FieldTypes.TextField _portfolioTitle;
        
        private Synthesis.FieldTypes.TextField _title;
        
        private Synthesis.FieldTypes.ImageField _image;
        
        private Synthesis.FieldTypes.RichTextField _portfolioBody;
        
        public Portfolio(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Portfolio(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Portfolio";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{96BF0B0D-7FFD-47D3-854E-C9E1C98DF8DF}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the PortfolioTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("portfoliotitle")]
        public Synthesis.FieldTypes.Interfaces.ITextField PortfolioTitle {
            get {
                if (_portfolioTitle == null) {
                    _portfolioTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{480B41FD-DE3A-49FE-ABA9-EFABCE9FEC87}"], "/sitecore/templates/Project/Example/Page Type Template/Portfolio", "PortfolioTitle"), this.GetSearchFieldValue("portfoliotitle"));
                }
                return _portfolioTitle;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0ED549A-2C9A-4D45-9D47-C670BB6B0C54}"], "/sitecore/templates/Project/Example/Page Type Template/Portfolio", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image {
            get {
                if (_image == null) {
                    _image = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{89FA71B6-5B2B-49A1-A082-79DE07A2A24E}"], "/sitecore/templates/Project/Example/Page Type Template/Portfolio", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image;
            }
        }
        
        /// <summary>Represents the PortfolioBody field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("portfoliobody")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField PortfolioBody {
            get {
                if (_portfolioBody == null) {
                    _portfolioBody = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F7E753D8-1700-426F-98A0-D0C8D4649B70}"], "/sitecore/templates/Project/Example/Page Type Template/Portfolio", "PortfolioBody"), this.GetSearchFieldValue("portfoliobody"));
                }
                return _portfolioBody;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class PortfolioInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{96BF0B0D-7FFD-47D3-854E-C9E1C98DF8DF}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Portfolio(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Portfolio(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/Portfolios template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class Portfolios : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.IPortfoliosItem {
        
        private Synthesis.FieldTypes.TextField _title;
        
        public Portfolios(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Portfolios(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Portfolios";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A8470C4A-7757-464D-9573-2B685AC6A2F2}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Title {
            get {
                if (_title == null) {
                    _title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0ED549A-2C9A-4D45-9D47-C670BB6B0C54}"], "/sitecore/templates/Project/Example/Page Type Template/Portfolios", "Title"), this.GetSearchFieldValue("title"));
                }
                return _title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class PortfoliosInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A8470C4A-7757-464D-9573-2B685AC6A2F2}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Portfolios(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Portfolios(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Example/Page Type Template/test-area template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class testarea : global::Synthesis.StandardTemplateItem, global::Synthesis.Model.Project.Example.PageTypeTemplate.ItestareaItem {
        
        public testarea(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public testarea(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "test-area";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{AF871E1D-D32E-4090-AB97-BCDE8565780D}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class testareaInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{AF871E1D-D32E-4090-AB97-BCDE8565780D}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new testarea(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new testarea(searchFields);
        }
    }
}
