---
ID: "d03b0237-cd49-4083-a256-73cc25b3013b"
Parent: "ff290707-f5ef-48bf-be32-b350e364dbfc"
Template: "ff290707-f5ef-48bf-be32-b350e364dbfc"
Path: /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180925T064128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
