---
ID: "704c8ebe-e8ea-4c42-bba2-b19c0b2af5d1"
Parent: "af871e1d-d32e-4090-ab97-bcde8565780d"
Template: "af871e1d-d32e-4090-ab97-bcde8565780d"
Path: "/sitecore/templates/Project/Example/Page Type Template/test-area/__Standard Values"
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{839EC050-E0AB-4B9F-BF6B-9ACF2683304C}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180927T071311Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
